export default function page() {
  return (
    <div className="text-white pt-28">
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Beatae porro nostrum enim quo sed a facere voluptate aperiam, soluta impedit ratione quisquam reiciendis, doloribus debitis obcaecati fugiat cumque! Nostrum saepe veniam praesentium! Et nostrum deserunt accusamus, accusantium ducimus harum quia reprehenderit aperiam aut provident, eaque facilis repudiandae vero fugit veritatis iure recusandae corporis aliquam, qui laborum at debitis sunt perferendis reiciendis. Architecto, exercitationem placeat! Possimus, doloremque enim, suscipit, rem quod ullam nulla recusandae at quasi voluptatibus unde ab a iure illo aliquid eum voluptates odio similique eius sequi! Perferendis consequuntur laudantium incidunt mollitia numquam illo molestias quam, dolor saepe cupiditate laboriosam facilis tempora? Similique reprehenderit esse blanditiis tempore adipisci dolores optio molestias animi dignissimos! Asperiores repellat fuga eum tenetur minus minima eos sed quaerat tempore repudiandae iusto at ut ullam sunt earum temporibus, accusantium laboriosam nulla maiores dolorum ea mollitia rem animi et? Ratione necessitatibus facilis magni ea eius voluptatum error reiciendis, quis aliquid perferendis suscipit inventore excepturi minus quos cum quod unde aut quasi quisquam eligendi nisi. Sequi nemo repellat quis optio ea accusamus atque, minima excepturi, sapiente enim suscipit culpa adipisci error officia perferendis non quas reprehenderit quisquam dicta corrupti obcaecati, eos at quo. Debitis repellat velit minima beatae voluptatibus cum, quo tempora ea doloremque similique aperiam explicabo sit sint atque deleniti. Nihil expedita enim maiores? Necessitatibus minus excepturi temporibus laborum doloremque harum, officiis tempore ipsa labore adipisci eos quia, accusamus dolorum dolore hic a omnis dolores. Deserunt architecto odit suscipit ad sunt quos iusto aliquam natus possimus?
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus suscipit ab vitae! Aspernatur, in saepe! Qui obcaecati eum error cum ab, adipisci blanditiis similique omnis exercitationem! Odit vero tenetur incidunt perferendis velit rerum eaque voluptate quasi. Molestiae, minus. Deserunt dolorum eveniet id debitis sint asperiores numquam doloribus voluptates voluptas, dolores enim et autem nihil praesentium voluptatum odit non provident sunt beatae obcaecati! Et, reprehenderit harum! Beatae natus, quisquam hic officia repudiandae consequatur asperiores earum recusandae, eos quae possimus eaque, perferendis necessitatibus nostrum consectetur vel qui velit fugiat. Tempore voluptates cum vero? Fuga aspernatur maxime ut? Consequatur placeat expedita odio. Beatae, dolor quam pariatur ducimus, quis asperiores praesentium corporis temporibus vitae tenetur odit qui assumenda illum. Sit eum, at fuga magni suscipit aliquid deleniti veniam dolorum neque rerum harum, cum quaerat eaque pariatur reiciendis maiores tempora optio aspernatur saepe. Voluptatum rem omnis at cum quibusdam minima commodi debitis asperiores deserunt. Eius, temporibus repudiandae, ratione eum rem autem, reiciendis voluptatum facilis impedit omnis mollitia maxime. Labore repellendus incidunt necessitatibus impedit explicabo eaque itaque illum ipsa repudiandae porro sequi debitis cum non culpa eum qui inventore minus suscipit facilis, quae ad, fugit saepe. Voluptas ab aliquid asperiores possimus illo, laboriosam qui et! Nostrum?
    </p>
    </div>
  )
}